### PR TITLE
Updates to fix issues with v1.61

### PR DESCRIPTION
**Pull request by Goldentoenail**
Hope these are of use to you.
I have tested and debugged the changes as best as I can.

These files have been built upon the Github repositories for ...
CS_CoreLib_v1.5.13
Slimefun v4.1.3
ExoticGarden v1.6.1

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Fix your format, also state what changes you made and overall it kinda looks like you broke more than you fixed...

**Comment by Goldentoenail** [comment]
It is kind of sad that you are so abrupt.


You should make the build and check it out in-game.

This is probably why it has been broken for the past few versions now!

________________________________

**Comment by Goldentoenail** [comment]
Oh, I forgot to re-add the EGBlocks class back at the first instance. Try it again.


Fix my format? The format of what? I am not aware of anything being non-standard.


________________________________

**Comment by Goldentoenail** [comment]
Oh, I see that the Github compare function seems to be out of synchronization.


I will rebuild the files. And hopefully there will be an improvement to the comparison.


________________________________

**Comment by Goldentoenail** [comment]
Can you see the new changes or do I need to make a new pull request?



________________________________

**Comment by TheBusyBiscuit** [comment]
You will have to propose a new pull request.

**Comment by TheBusyBiscuit** [comment]
But I can do that for you as well.

**Comment by TheBusyBiscuit** [comment]
https://github.com/TheBusyBiscuit/ExoticGarden/pull/4/files

By the way, please dont do that changes.txt / ReadMe.md thing, just put that stuff into your PR message.

**Comment by TheBusyBiscuit** [comment]
Even with your newest changes, the EGPlant class is there for a reason, fruits are otherwise not edible.
And dont do that chance thing on LeavesDecay. The chance is applied when generating the leave.

**Comment by Goldentoenail** [comment]
The fruits I have tested are edible.
The drops are failing due to incompatibility with EGPlant and the Boolean edible ,this is why using EGBlock does work.


I had no idea about the leaves having a drop probability already.

________________________________

**Pull request closed without merging**
