### PR TITLE
Adds Netherite plant

### PR DESCRIPTION
**Pull request by Skizzles**
Adds Netherite Plant with recipe of 4x Netherite Block and 1 Emerald Plant due to being end game and difficult to get.

### CODE REVIEW

**Comment by WalshyDev** [comment]
Head texture: http://textures.minecraft.net/texture/67e29a58c060511ff0350241c9c86496947d8f84bf32f2df35ebe3742f0e2029

**Comment by Skizzles** [comment]
Oops

**Comment by TheBusyBiscuit** [comment]
Are we sure that the plant should give ingots directly and not just ancient scrap?

**Comment by Skizzles** [comment]
@WalshyDev This one better? http://textures.minecraft.net/texture/27957f895d7bc53423a35aac59d584b41cc30e040269c955e451fe680a1cc049

A lot of the textures are odd.

**Comment by Skizzles** [comment]
@TheBusyBiscuit 

My players believed it should give the ingot directly, this is also why I made the plant more difficult with a block recipe.

**Comment by TheBusyBiscuit** [comment]
> @TheBusyBiscuit
> 
> My players believed it should give the ingot directly, this is also why I made the plant more difficult with a block recipe.

Okay then, I'm gonna trust them on that.

**Review by TheBusyBiscuit — APPROVED** [review]

**Pull request merged**
