### PR TITLE
Implement Copper Plant

### PR DESCRIPTION
**Pull request by BluGhostYT**
This PR was attempted before, but was denied due to wrong texture. I will do this for them

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Why a diamond plant though?

**Comment by BluGhostYT** [comment]
Would you rather it be a gold plant instead? I was told to change it by Walshy

**Comment by TheBusyBiscuit** [comment]
Well, Gold Plants would make more sense, they are closer to copper than diamonds at least.

**Comment by BluGhostYT** [comment]
No worries, will fix

**Comment by TheBusyBiscuit** [comment]
I also think the Output should probably be more than one piece of dust.
More like 8, since you will need 8 magical essences to craft it, otherwise you either waste a stack of bonemeal on one plant or you need to get at least a dozen plants just to get a single piece of dust...

**Comment by BluGhostYT** [comment]
There we go, that should do it.

**Pull request merged**
